M48
; DRILL file {KiCad 9.0.5} date 2026-02-03T11:17:31+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-02-03T11:17:31+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.5
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.940
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C1.020
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C2.050
%
G90
G05
T1
X83.03Y-152.94
X83.03Y-155.94
T2
X58.03Y-109.58
X58.03Y-115.93
T3
X66.75Y-147.5
X83.25Y-147.5
M30
